### ISSUE TITLE
Supporting Symfony 5

### ISSUE THREAD

**Issue by walva** [IDCI-Consulting/IDCIKeycloakSecurityBundle#13]
Hello !

I wanted to integrate IDCIKeycloakSecurityBundle in my Symfony 5 but I ran into several problems. The main problem is that the [KeycloakUserProvider::loadUserByUsername](https://github.com/IDCI-Consulting/IDCIKeycloakSecurityBundle/blob/master/Security/User/KeycloakUserProvider.php#L28) is invalid with the new [ProviderInterface::loadUserByUsername](https://github.com/symfony/security-core/commit/38f92636925745488e561fe31e6560b274e18274) signature introduce in Symfony 5.

To solve this issue, I don"t rely on the userProvider in the method [KeycloakAuthenticator::getUser](https://github.com/IDCI-Consulting/IDCIKeycloakSecurityBundle/blob/master/Security/Authenticator/KeycloakAuthenticator.php#L50).
Instead, I use this piece of code:

```
public function getUser($accessToken, UserProviderInterface $userProvider)
    {
        $keycloakClient = $this->getClient();
        $keycloakUser   = $keycloakClient->fetchUserFromToken($accessToken);

        $keycloakUserRawResponse = $keycloakUser->toArray();

        $user = new KeycloakUser(/** params... */);
        return $user;
    }
```
Obviously this piece of code contains business specific code.

I thought the new Interface was breaking the bundle but actually the implementation should change a bit. I started a [discussion](https://github.com/symfony/symfony/issues/37333) on the symfony project about this.

**Comment by konandrum** [comment]
I will work on this issue

**Comment by Guite** [comment]
Feel free to try this fork: https://github.com/Guite/IDCIKeycloakSecurityBundle/ which includes refactorings for the new authenticator system.

**Comment by konandrum** [comment]
Done with v2.0.0
