### ISSUE TITLE
Supporting Symfony 6

### ISSUE THREAD

**Issue by mariantrifu** [IDCI-Consulting/IDCIKeycloakSecurityBundle#24]
It looks like Symfony 6 is not supported. I've tested and encountered a lot of issues. It looks like the security bundle had a lot of changes.

**Comment by Grazulex** [comment]
No response about a symfony 6 support ? Can we help ?

**Comment by Guite** [comment]
Feel free to try this fork: https://github.com/Guite/IDCIKeycloakSecurityBundle/

**Comment by konandrum** [comment]
Hi, I will work on symfony6 support and compatibility with last keycloak version (20)

**Comment by konandrum** [comment]
> Feel free to try this fork: https://github.com/Guite/IDCIKeycloakSecurityBundle/ which includes refactorings for the new authenticator system.

Thanks a lot for the great job you have done !

**Comment by Guite** [comment]
Thank you for the praise. Unfortunately, we don't use the bundle anymore because we integrate Keycloak differently into our service architecture. If someone wants to adopt the fork, I would not be ungrateful ;-)

**Comment by konandrum** [comment]
> Thank you for the praise. Unfortunately, we don't use the bundle anymore because we integrate Keycloak differently into our service architecture. If someone wants to adopt the fork, I would not be ungrateful ;-)

I'm working on it now, will be available soon ;)

**Comment by konandrum** [comment]
Done, new v2.0.0 version available thanks to @Guite for the main job !
