### ISSUE TITLE
Symfony 6.2+ - AbstractGuardAuthenticator 

### ISSUE THREAD

**Issue by enkaho** [IDCI-Consulting/IDCIKeycloakSecurityBundle#27]
I've the following error from [/vendor/idci/keycloak-security-bundle/Security/Authenticator/KeycloakBearerAuthenticator.php ](https://github.com/IDCI-Consulting/IDCIKeycloakSecurityBundle/blob/master/Security/Authenticator/KeycloakBearerAuthenticator.php#L1)(line 15)

```error
Attempted to load class "AbstractGuardAuthenticator" from namespace "Symfony\Component\Security\Guard".    
Did you forget a "use" statement for another namespace?
```

**Comment by konandrum** [comment]
Must be fixed with v2.0.1
